return {
    ["Beaver Totem"] = {{
        {
        id = "beaver_bow_gnawing",
        weaponType = "Bow",
        displayName = "The Gnawing",
        description = "Endlessly persistent",
        rarity = "Common",
        },
        {
        id = "beaver_bow_sentinel",
        weaponType = "Bow",
        displayName = "The Sentinel",
        description = "A worthy guardian",
        rarity = "Common",
        },
        {
        id = "beaver_flyblade_tireless",
        weaponType = "Flyblade",
        displayName = "The Tireless",
        description = "One who does not give in",
        rarity = "Common",
        },
        {
        id = "beaver_flyblade_thumper",
        weaponType = "Flyblade",
        displayName = "The Thumper",
        description = "Flat of tail",
        rarity = "Common",
        },
        {
        id = "beaver_heavy_logger",
        weaponType = "Heavy",
        displayName = "The Logger",
        description = "A feller of mighty trees",
        rarity = "Common",
        },
        {
        id = "beaver_heavy_bulwark",
        weaponType = "Heavy",
        displayName = "The Bulwark",
        description = "A steadfast force",
        rarity = "Rare",
        },
        {
        id = "beaver_longblade_resolute",
        weaponType = "Long Blade",
        displayName = "The Resolute",
        description = "A determined fellow",
        rarity = "Rare",
        },
        {
        id = "beaver_longblade_hewen",
        weaponType = "Long Blade",
        displayName = "The Hewen",
        description = "Knower of the fallen",
        rarity = "Common",
        },
        {
        id = "beaver_magick_creator",
        weaponType = "Magick",
        displayName = "The Creator",
        description = "A maker of worlds",
        rarity = "Uncommon",
        },
        {
        id = "beaver_magick_shaper",
        weaponType = "Magick",
        displayName = "The Shaper",
        description = "Crafter of meaning",
        rarity = "Uncommon",
        },
        {
        id = "beaver_polearm_toiling",
        weaponType = "Polearm",
        displayName = "The Toiling",
        description = "Hardest of workers",
        rarity = "Common",
        },
        {
        id = "beaver_polearm_carver",
        weaponType = "Polearm",
        displayName = "The Carver",
        description = "Maker of perfect forms",
        rarity = "Rare",
        },
        {
        id = "beaver_shield_ally",
        weaponType = "Shield",
        displayName = "The Ally",
        description = "To be trusted",
        rarity = "Common",
        },
        {
        id = "beaver_shield_mason",
        weaponType = "Shield",
        displayName = "The Mason",
        description = "Architect of defence",
        rarity = "Uncommon",
        },
        {
        id = "beaver_shortblade_master",
        weaponType = "Short Blade",
        displayName = "The Master",
        description = "Capable and determined",
        rarity = "Common",
        },
        {
        id = "beaver_shortblade_chipper",
        weaponType = "Short Blade",
        displayName = "The Chipper",
        description = "Slow and steady",
        rarity = "Common",
        }
    }},
    ["Deer Totem"] = {{
        {
        id = "deer_bow_noble",
        weaponType = "Bow",
        displayName = "The Noble",
		description = "Having the purest intentions",
        rarity = "Rare",
        },
        {
        id = "deer_flyblade_regal",
        weaponType = "Flyblade",
        displayName = "The Regal",
		description = "Commander of the herd",
        rarity = "Uncommon",
        },
        {
        id = "deer_flyblade_pronged",
        weaponType = "Flyblade",
        displayName = "The Pronged",
		description = "A multifaceted creature",
        rarity = "Common",
        },
        {
        id = "deer_heavy_highborn",
        weaponType = "Heavy",
        displayName = "The Highborn",
		description = "Of noble blood",
        rarity = "Uncommon",
        },
        {
        id = "deer_heavy_warden",
        weaponType = "Heavy",
        displayName = "The Warden",
		description = "A steadfast force",
        rarity = "Common",
        },
        {
        id = "deer_longblade_marked",
        weaponType = "Long Blade",
        displayName = "The Marked",
		description = "The chosen leader",
        rarity = "Common",
        },
        {
        id = "deer_longblade_graceful",
        weaponType = "Long Blade",
        displayName = "The Graceful",
		description = "Moves effortlessly",
        rarity = "Common",
        },
        {
        id = "deer_magick_proud",
        weaponType = "Magick",
        displayName = "The Proud",
		description = "Unwavering confidence",
        rarity = "Common",
        },
        {
        id = "deer_magick_fleet",
        weaponType = "Magick",
        displayName = "The Fleet",
		description = "One of many",
        rarity = "Common",
        },
        {
        id = "deer_polearm_headlong",
        weaponType = "Polearm",
        displayName = "The Headlong",
		description = "Leader of the charge",
        rarity = "Rare",
        },
        {
        id = "deer_polearm_astute",
        weaponType = "Polearm",
        displayName = "The Astute",
		description = "Overseer of all",
        rarity = "Common",
        },
        {
        id = "deer_shield_protector",
        weaponType = "Shield",
        displayName = "The Protector",
		description = "Ward of the herd",
        rarity = "Common",
        },
        {
        id = "deer_shield_contender",
        weaponType = "Shield",
        displayName = "The Contender",
		description = "Challenger of rivals",
        rarity = "Common",
        },
        {
        id = "deer_shortblade_cleft",
        weaponType = "Short Blade",
        displayName = "The Cleft",
		description = "An attention divided",
        rarity = "Common",
        },
        {
        id = "deer_shortblade_swift",
        weaponType = "Short Blade",
        displayName = "The Swift",
		description = "Effortless and unwavering",
        rarity = "Common",
        }
    }},
    ["Duck Totem"] = {{
        {
        id = "duck_bow_yielding",
        weaponType = "Bow",
        displayName = "The Yielding",
		description = "Fluid as water",
        rarity = "Common",
        },
        {
        id = "duck_bow_voyager",
        weaponType = "Bow",
        displayName = "The Voyager",
		description = "Explorer of unknowns",
        rarity = "Rare",
        },
        {
        id = "duck_flyblade_ambling",
        weaponType = "Flyblade",
        displayName = "The Ambling",
		description = "A taker of time",
        rarity = "Common",
        },
        {
        id = "duck_flyblade_flurry",
        weaponType = "Flyblade",
        displayName = "The Flurry",
		description = "A whirl of wind and water",
        rarity = "Common",
        },
        {
        id = "duck_heavy_sodden",
        weaponType = "Heavy",
        displayName = "The Sodden",
		description = "A fair swimmer",
        rarity = "Uncommon",
        },
        {
        id = "duck_heavy_ripple",
        weaponType = "Heavy",
        displayName = "The Ripple",
		description = "Maker of waves",
        rarity = "Common",
        },
        {
        id = "duck_longblade_plunged",
        weaponType = "Long Blade",
        displayName = "The Plunged",
		description = "A natural diver",
        rarity = "Uncommon",
        },
        {
        id = "duck_longblade_splasher",
        weaponType = "Long Blade",
        displayName = "The Splasher",
		description = "Render of waters",
        rarity = "Common",
        },
        {
        id = "duck_magick_buoyant",
        weaponType = "Magick",
        displayName = "The Buoyant",
		description = "Floats over rough waters",
        rarity = "Rare",
        },
        {
        id = "duck_magick_current",
        weaponType = "Magick",
        displayName = "The Current",
		description = "Guides the great flow",
        rarity = "Common",
        },
        {
        id = "duck_polearm_drudger",
        weaponType = "Polearm",
        displayName = "The Drudger",
		description = "Fearless in the face of muck",
        rarity = "Common",
        },
        {
        id = "duck_polearm_waddler",
        weaponType = "Polearm",
        displayName = "The Waddler",
		description = "Wobbly yet effective",
        rarity = "Common",
        },
        {
        id = "duck_shield_sailor",
        weaponType = "Shield",
        displayName = "The Sailor",
		description = "Expert of the waters",
        rarity = "Common",
        },
        {
        id = "duck_shield_anchor",
        weaponType = "Shield",
        displayName = "The Anchor",
		description = "Resting in troubled waters",
        rarity = "Uncommon",
        },
        {
        id = "duck_shortblade_wader",
        weaponType = "Short Blade",
        displayName = "The Wader",
		description = "Lover of shallow waters",
        rarity = "Common",
        },
        {
        id = "duck_shortblade_sloshing",
        weaponType = "Short Blade",
        displayName = "The Sloshing",
		description = "A disorienting tempest",
        rarity = "Uncommon",
        }
    }},
    ["Rabbit Totem"] = {{
        {
        id = "rabbit_bow_ample",
        weaponType = "Bow",
        displayName = "The Ample",
        description = "Satisfied with things as they are",
        rarity = "Common",
        },
        {
        id = "rabbit_flyblade_rallying",
        weaponType = "Flyblade",
        displayName = "The Rallying",
        description = "A symbol of resilience",
        rarity = "Common",
        },
        {
        id = "rabbit_heavy_compelled",
        weaponType = "Heavy",
        displayName = "The Compelled",
        description = "Drawn by larger force",
        rarity = "Rare",
        },
        {
        id = "rabbit_heavy_stomping",
        weaponType = "Heavy",
        displayName = "The Stomping",
        description = "Shaker of soil",
        rarity = "Common",
        },
        {
        id = "rabbit_longblade_brawn",
        weaponType = "Long Blade",
        displayName = "The Brawn",
        description = "Well-muscled",
        rarity = "Rare",
        },
        {
        id = "rabbit_longblade_bounder",
        weaponType = "Long Blade",
        displayName = "The Bounder",
        description = "Taker of leaps",
        rarity = "Common",
        },
        {
        id = "rabbit_magick_springing",
        weaponType = "Magick",
        displayName = "The Springing",
        description = "Coiled and ready",
        rarity = "Common",
        },
        {
        id = "rabbit_polearm_rebound",
        weaponType = "Polearm",
        displayName = "The Rebound",
        description = "A symbol of health and luck",
        rarity = "Uncommon",
        },
        {
        id = "rabbit_polearm_bombardier",
        weaponType = "Polearm",
        displayName = "The Bombardier",
        description = "A thumper of feet",
        rarity = "Common",
        },
        {
        id = "rabbit_shield_sturdy",
        weaponType = "Shield",
        displayName = "The Sturdy",
        description = "Solid and secure",
        rarity = "Common",
        },
        {
        id = "rabbit_shield_targe",
        weaponType = "Shield",
        displayName = "The Targe",
        description = "Deflector of assaults",
        rarity = "Common",
        },
        {
        id = "rabbit_shortblade_punter",
        weaponType = "Short Blade",
        displayName = "The Punter",
        description = "A mighty kicker",
        rarity = "Common",
        },
        {
        id = "rabbit_shortblade_bolt",
        weaponType = "Short Blade",
        displayName = "The Bolt",
        description = "A rapid burst forth",
        rarity = "Uncommon",
        }
    }},
    ["Rat Totem"] = {{
        {
        id = "rat_bow_scourge",
        weaponType = "Bow",
        displayName = "The Scourge",
        description = "Bringer of blight",
        rarity = "Common",
        },
        {
        id = "rat_bow_slinker",
        weaponType = "Bow",
        displayName = "The Slinker",
        description = "A cunning stalker",
        rarity = "Common",
        },
        {
        id = "rat_flyblade_clever",
        weaponType = "Flyblade",
        displayName = "The Clever",
        description = "A cunning creature",
        rarity = "Uncommon",
        },
        {
        id = "rat_flyblade_skitter",
        weaponType = "Flyblade",
        displayName = "The Skitter",
        description = "A blur of sudden movement",
        rarity = "Common",
        },
        {
        id = "rat_heavy_thief",
        weaponType = "Heavy",
        displayName = "The Thief",
        description = "Takes what is wanted",
        rarity = "Common",
        },
        {
        id = "rat_heavy_usurper",
        weaponType = "Heavy",
        displayName = "The Usurper",
        description = "A seizer of power",
        rarity = "Uncommon",
        },
        {
        id = "rat_longblade_rascal",
        weaponType = "Long Blade",
        displayName = "The Rascal",
        description = "Roguishly endearing",
        rarity = "Rare",
        },
        {
        id = "rat_longblade_shadow",
        weaponType = "Long Blade",
        displayName = "The Shadow",
        description = "A presence unseen",
        rarity = "Uncommon",
        },
        {
        id = "rat_magick_blighted",
        weaponType = "Magick",
        displayName = "The Blighted",
        description = "Knower of the wastes",
        rarity = "Common",
        },
        {
        id = "rat_magick_forager",
        weaponType = "Magick",
        displayName = "The Forager",
        description = "Knower of the wastes",
        rarity = "Common",
        },
        {
        id = "rat_polearm_sly",
        weaponType = "Polearm",
        displayName = "The Sly",
        description = "Self-satisfied",
        rarity = "Uncommon",
        },
        {
        id = "rat_polearm_biting",
        weaponType = "Polearm",
        displayName = "The Biting",
        description = "A toothy thing",
        rarity = "Common",
        },
        {
        id = "rat_shield_lurker",
        weaponType = "Shield",
        displayName = "The Lurker",
        description = "A watcher and waiter",
        rarity = "Common",
        },
        {
        id = "rat_shield_tunneler",
        weaponType = "Shield",
        displayName = "The Tunneler",
        description = "Carver of secrets",
        rarity = "Rare",
        },
        {
        id = "rat_shortblade_scavenger",
        weaponType = "Short Blade",
        displayName = "The Scavenger",
        description = "A seeker of opportunities",
        rarity = "Common",
        },
        {
        id = "rat_shortblade_nibbling",
        weaponType = "Short Blade",
        displayName = "The Nibbling",
        description = "Persistent and nagging",
        rarity = "Common",
        }
    }},
    ["Squirrel Totem"] = {{
        {
        id = "squirrel_bow_spry",
        weaponType = "Bow",
        displayName = "The Spry",
        description = "Willing and able",
        rarity = "Uncommon",
        },
        {
        id = "squirrel_bow_lookout",
        weaponType = "Bow",
        displayName = "The Lookout",
        description = "A sharp gaze from above",
        rarity = "Common",
        },
        {
        id = "squirrel_flyblade_messenger",
        weaponType = "Flyblade",
        displayName = "The Messenger",
        description = "Breaker of news",
        rarity = "Common",
        },
        {
        id = "squirrel_flyblade_climber",
        weaponType = "Flyblade",
        displayName = "The Climber",
        description = "Finding purchase above",
        rarity = "Rare",
        },
        {
        id = "squirrel_heavy_mercurial",
        weaponType = "Heavy",
        displayName = "The Mercurial",
        description = "The one between all others",
        rarity = "Common",
        },
        {
        id = "squirrel_heavy_fluffy",
        weaponType = "Heavy",
        displayName = "The Fluffy",
        description = "A great puff of fur",
        rarity = "Uncommon",
        },
        {
        id = "squirrel_longblade_lithe",
        weaponType = "Long Blade",
        displayName = "The Lithe",
        description = "Swift and slender",
        rarity = "Common",
        },
        {
        id = "squirrel_longblade_glider",
        weaponType = "Long Blade",
        displayName = "The Glider",
        description = "Soaring through trees",
        rarity = "Uncommon",
        },
        {
        id = "squirrel_magick_spirited",
        weaponType = "Magick",
        displayName = "The Spirited",
        description = "Full of life",
        rarity = "Rare",
        },
        {
        id = "squirrel_magick_dart",
        weaponType = "Magick",
        displayName = "The Dart",
        description = "Sudden unerring speed",
        rarity = "Common",
        },
        {
        id = "squirrel_polearm_nimble",
        weaponType = "Polearm",
        displayName = "The Nimble",
        description = "Quick and agile",
        rarity = "Common",
        },
        {
        id = "squirrel_polearm_lively",
        weaponType = "Polearm",
        displayName = "The Lively",
        description = "Of boundless energy",
        rarity = "Common",
        },
        {
        id = "squirrel_shield_impish",
        weaponType = "Shield",
        displayName = "The Impish",
        description = "Just a scurry away",
        rarity = "Common",
        },
        {
        id = "squirrel_shield_stasher",
        weaponType = "Shield",
        displayName = "The Stasher",
        description = "A collector of things",
        rarity = "Common",
        },
        {
        id = "squirrel_shortblade_blitz",
        weaponType = "Short Blade",
        displayName = "The Blitz",
        description = "Everywhere at once",
        rarity = "Common",
        },
        {
        id = "squirrel_shortblade_acrobat",
        weaponType = "Short Blade",
        displayName = "The Acrobat",
        description = "Flawless flipper",
        rarity = "Rare",
        }
    }}
}
